// Mocks generated by Mockito 5.3.2 from annotations
// in cotizacion_dm/test/application/form_employee_bloc/form_employee_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cotizacion_dm/core/domain/employee/employee.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmployee_0 extends _i1.SmartFake implements _i2.Employee {
  _FakeEmployee_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EmployeeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeService extends _i1.Mock implements _i2.EmployeeService {
  MockEmployeeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.Employee>> all() => (super.noSuchMethod(
        Invocation.method(
          #all,
          [],
        ),
        returnValue: _i3.Future<List<_i2.Employee>>.value(<_i2.Employee>[]),
      ) as _i3.Future<List<_i2.Employee>>);
  @override
  _i3.Future<_i2.Employee> findById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i3.Future<_i2.Employee>.value(_FakeEmployee_0(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.Employee>);
  @override
  _i3.Future<_i2.Employee> save(_i2.Employee? employee) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [employee],
        ),
        returnValue: _i3.Future<_i2.Employee>.value(_FakeEmployee_0(
          this,
          Invocation.method(
            #save,
            [employee],
          ),
        )),
      ) as _i3.Future<_i2.Employee>);
  @override
  _i3.Future<_i2.Employee> update(_i2.Employee? employee) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [employee],
        ),
        returnValue: _i3.Future<_i2.Employee>.value(_FakeEmployee_0(
          this,
          Invocation.method(
            #update,
            [employee],
          ),
        )),
      ) as _i3.Future<_i2.Employee>);
  @override
  _i3.Future<int> delete(_i2.Employee? employee) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [employee],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
